const { withAppBuildGradle } = require('@expo/config-plugins');

/** Suppress Kotlin/C++ noise from third-party native modules during release builds. */
module.exports = function withAndroidBuild(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      return config;
    }

    const block = `
// @generated by plugins/withAndroidBuild.js
tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    compilerOptions {
        freeCompilerArgs.addAll([
            "-Xno-deprecation-warnings",
            "-Xsuppress-version-warnings",
        ])
    }
}
`;

    if (!config.modResults.contents.includes('withAndroidBuild.js')) {
      config.modResults.contents += block;
    }

    return config;
  });
};
